openapi: "3.0.0"
info:
  title: Nuts consent bridge API spec
  description: API specification for RPC services available at the nuts-consent-bridge
  version: 0.1.0
  license:
    name: GPLv3
paths:
  $ref: 'nuts-consent-bridge.yaml#/paths'

components:
  $ref: 'nuts-consent-bridge.yaml#/components'