openapi: "3.0.0"
info:
  title: Nuts service crypto spec
  description: API specification for crypto services available within nuts service space
  version: 0.1.0
  license:
    name: GPLv3
paths:
  /consent/validate:
    post:
      summary: "Send a fhir consent record for validation. If valid the result will also include all accessible resources."
      operationId: validate
      tags:
        - consent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: "Request has been parsed. Result object holds outcome, errors and/or accessible resources."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
        '400':
          description: incorrect data
          content:
            text/plain:
              example:
                no request body
components:
  schemas:
    ValidationResponse:
      description: "Result of validation request with the outcome"
      required:
        - outcome
      properties:
        outcome:
          type: string
          enum: ["valid", "invalid"]
        validationErrors:
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
        consent:
          $ref: "#/components/schemas/SimplifiedConsent"
    ValidationError:
      description: "Error that occurred while validating the given consent record"
      required:
        - type
        - message
      properties:
        type:
          type: string
          enum: ["syntax", "constraint", "policy"]
          description: "Type of error: syntax (json is broken), constraint (json is not a valid fhir resource), policy (current Nuts node settings do not allow this record)"
        message:
          type: string
          description: "The actual error"
    SimplifiedConsent:
      description: "Simplified consent record"
      required:
        - actors
        - custodian
        - resources
        - subject
      properties:
        actors:
          type: array
          items:
            $ref: "#/components/schemas/Identifier"
        custodian:
          $ref: "#/components/schemas/Identifier"
        resources:
          description: "Array of fhir resources"
          type: array
          items:
            type: string
        subject:
          $ref: "#/components/schemas/Identifier"
    Identifier:
      type: string
      description: >
        Generic identifier used for representing BSN, agbcode, etc.
        It's always constructed as an URN followed by a double colon (::) and then the identifying value of the given URN
      example: |
        * urn:nuts:bsn::999999990
        * urn:nuts:agbcode::00000007
        * urn:nuts:endpoint::consent
        * urn:ietf:rfc:1779::O=Nedap, OU=Healthcare, C=NL, ST=Gelderland, L=Groenlo, CN=nuts_corda_development_local